# Generated by Django 4.2.23 on 2025-07-02 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_name', models.CharField(max_length=120)),
                ('amount', models.FloatField()),
                ('debited_date', models.DateField(auto_now_add=True)),
                ('debited_month', models.CharField(choices=[('Registration', 'Registration'), ('September', 'Meskerem/September'), ('October', 'Tqmt/October'), ('November', 'Hdar/November'), ('December', 'Tehsas/December'), ('January', 'Tr/January'), ('February', 'Yekatit/February'), ('March', 'Megabit/March'), ('April', 'Miyaziya/April'), ('May', 'Gnbot/May'), ('June', 'Sene/June')], max_length=120)),
                ('payment_type', models.CharField(choices=[('monthly', 'Monthly'), ('after_class', 'After Class Reading')], max_length=120)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.studentregistration')),
            ],
        ),
    ]
