# Generated by Django 4.2.23 on 2025-07-09 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_studentregistration_parent'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('student', 'debited_month', 'payment_type')},
        ),
    ]
