# Generated by Django 4.2.23 on 2025-07-11 05:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-debited_date_time']},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='debited_date',
        ),
        migrations.AddField(
            model_name='payment',
            name='debited_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('pending', 'Pending')], max_length=20, null=True),
        ),
    ]
