# Generated by Django 4.2.23 on 2025-07-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payment_debited_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='debited_month',
            field=models.CharField(blank=True, choices=[('September', 'Meskerem/September'), ('October', 'Tqmt/October'), ('November', 'Hdar/November'), ('December', 'Tehsas/December'), ('January', 'Tr/January'), ('February', 'Yekatit/February'), ('March', 'Megabit/March'), ('April', 'Miyaziya/April'), ('May', 'Gnbot/May'), ('June', 'Sene/June')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('Registration', 'Registration'), ('monthly', 'Monthly'), ('after_class', 'After Class Reading')], max_length=120),
        ),
    ]
