# Generated by Django 4.2.23 on 2025-08-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_payment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_receipt_image',
            field=models.ImageField(default=None, upload_to='receipts/'),
            preserve_default=False,
        ),
    ]
