# Generated by Django 4.2.23 on 2025-09-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_payment_payment_receipt_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payer_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Registration', 'Registration'), ('monthly', 'Monthly'), ('after_class', 'After Class Reading')], max_length=120, null=True),
        ),
    ]
