# Generated by Django 4.2.23 on 2025-09-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_payment_payer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='debited_month',
            field=models.CharField(choices=[('September', 'Meskerem/September'), ('October', 'Tqmt/October'), ('November', 'Hdar/November'), ('December', 'Tehsas/December'), ('January', 'Tr/January'), ('February', 'Yekatit/February'), ('March', 'Megabit/March'), ('April', 'Miyaziya/April'), ('May', 'Gnbot/May'), ('June', 'Sene/June')], default='unknown', max_length=120),
            preserve_default=False,
        ),
    ]
