# Generated by Django 4.2.23 on 2025-07-02 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parents', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middlename', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=15)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField()),
                ('image_file', models.ImageField(upload_to='')),
                ('address', models.CharField(max_length=60)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('kebele_wereda', models.CharField(max_length=50)),
                ('kfleketema', models.CharField(max_length=50)),
                ('hous_number', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parents.parent')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
