# Generated by Django 4.2.23 on 2025-07-09 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_studentregistration_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregistration',
            name='user',
        ),
    ]
