# Generated by Django 4.2.23 on 2025-07-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_studentregistration_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentregistration',
            old_name='middlename',
            new_name='middle_name',
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='join_year',
            field=models.CharField(default=18, max_length=2),
            preserve_default=False,
        ),
    ]
