# Generated by Django 4.2.23 on 2025-07-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_rename_middlename_studentregistration_middle_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='student_id',
            field=models.CharField(default=7, max_length=20),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='join_year',
            field=models.CharField(default='25', max_length=2),
        ),
    ]
