# Generated by Django 4.2.23 on 2025-07-28 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_studentregistration_student_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregistration',
            name='student_id',
        ),
    ]
