# Generated by Django 4.2.23 on 2025-08-20 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('students', '0007_remove_studentregistration_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='studentregistration',
            old_name='kebele_wereda',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='studentregistration',
            old_name='kfleketema',
            new_name='kfle_ketema',
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='address',
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='common.grade'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='common.section'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='wereda',
            field=models.CharField(default='Daletiy', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.academicyear')),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.grade')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.section')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.studentregistration')),
            ],
            options={
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
