# Generated by Django 4.2.23 on 2025-08-24 09:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0003_rename_emetgencycontact_emergencycontact'),
        ('students', '0008_academicyear_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='enrollment_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='parents.parent'),
        ),
    ]
