# Generated by Django 4.2.23 on 2025-08-27 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_studentregistration_registration_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentregistration',
            options={'ordering': ['-registration_date']},
        ),
    ]
