# Generated by Django 4.2.23 on 2025-08-31 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_studentregistration_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='image_file',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
