# Generated by Django 4.2.23 on 2025-09-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0011_alter_emergencycontact_options_alter_parent_options_and_more'),
        ('students', '0012_alter_studentregistration_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregistration',
            name='parent',
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='parent',
            field=models.ManyToManyField(related_name='children', to='parents.parent'),
        ),
    ]
