# Generated by Django 4.2.23 on 2025-09-01 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_remove_studentregistration_parent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentregistration',
            old_name='parent',
            new_name='parents',
        ),
    ]
