# Generated by Django 4.2.23 on 2025-09-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_alter_studentregistration_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='image_file',
            field=models.ImageField(default='knowledge1_aFn8hfk.jpg', upload_to='photos/'),
        ),
    ]
