# Generated by Django 4.2.23 on 2025-09-10 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0015_alter_emergencycontact_image_file_and_more'),
        ('students', '0016_alter_studentregistration_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregistration',
            name='parents',
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='parents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='parents.parent'),
        ),
    ]
