# Generated by Django 4.2.23 on 2025-09-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0015_alter_emergencycontact_image_file_and_more'),
        ('students', '0017_remove_studentregistration_parents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregistration',
            name='parents',
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='parents',
            field=models.ManyToManyField(related_name='children', to='parents.parent'),
        ),
    ]
