# Generated by Django 4.2.23 on 2025-09-14 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('students', '0018_remove_studentregistration_parents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='common.grade'),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='image_file',
            field=models.ImageField(blank=True, default='knowledge1_aFn8hfk.jpg', null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='common.section'),
        ),
    ]
