# Generated by Django 4.2.23 on 2025-10-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['grade_name']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['section_name']},
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_name',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_name',
            field=models.CharField(max_length=50),
        ),
    ]
