# Generated by Django 4.2.23 on 2025-07-02 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_first_name', models.CharField(max_length=100)),
                ('father_middlename', models.CharField(max_length=100)),
                ('father_last_name', models.CharField(max_length=100)),
                ('father_age', models.IntegerField()),
                ('father_image_file', models.ImageField(upload_to='')),
                ('mother_first_name', models.CharField(max_length=100)),
                ('mother_middlename', models.CharField(max_length=100)),
                ('mother_last_name', models.CharField(max_length=100)),
                ('mother_age', models.IntegerField()),
                ('mother_image_file', models.ImageField(upload_to='')),
                ('address', models.CharField(max_length=60)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=60)),
                ('owner', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother')], max_length=30)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='parents.parent')),
            ],
        ),
    ]
