# Generated by Django 4.2.23 on 2025-08-24 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_academicyear_and_more'),
        ('parents', '0002_remove_parent_address_remove_parent_user_parent_city_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmetgencyContact',
            new_name='EmergencyContact',
        ),
    ]
