# Generated by Django 4.2.23 on 2025-08-25 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0003_rename_emetgencycontact_emergencycontact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='education_level',
            new_name='father_education_level',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='ocupation',
            new_name='father_ocupation',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='work_place',
            new_name='father_work_place',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='student',
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parents.parent'),
        ),
        migrations.AddField(
            model_name='parent',
            name='mother_education_level',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parent',
            name='mother_ocupation',
            field=models.CharField(default='house wife', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parent',
            name='mother_work_place',
            field=models.CharField(default='home', max_length=50),
            preserve_default=False,
        ),
    ]
