# Generated by Django 4.2.23 on 2025-08-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0004_rename_education_level_parent_father_education_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='father_age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='father_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='father_image_file',
            new_name='image_file',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='father_last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='father_middlename',
            new_name='middle_name',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='father_ocupation',
            new_name='ocupation',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='father_work_place',
            new_name='work_place',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='father_education_level',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='mother_age',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='mother_education_level',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='mother_first_name',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='mother_image_file',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='mother_last_name',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='mother_middlename',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='mother_ocupation',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='mother_work_place',
        ),
        migrations.AddField(
            model_name='parent',
            name='education_level',
            field=models.CharField(choices=[('none', 'No Formal Education'), ('primary', 'Primary'), ('secondary', 'Secondary'), ('highschool', 'High School'), ('diploma', 'Diploma'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD'), ('other', 'Other')], default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parent',
            name='role',
            field=models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('grandmother', 'Grandmother'), ('grandfather', 'Grandfather'), ('other', 'Other')], default='unknow', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='owner',
            field=models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('uncle', 'Uncle'), ('other', 'Other')], max_length=30),
        ),
    ]
