# Generated by Django 4.2.23 on 2025-08-26 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_enrollment_enrollment_date_and_more'),
        ('parents', '0005_rename_father_age_parent_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='phone_num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parents.phonenumber'),
        ),
        migrations.AddField(
            model_name='parent',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='kfle_ketema',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='relationship',
            field=models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('grandmother', 'Grandmother'), ('grandfather', 'Grandfather'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency', to='students.studentregistration'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='wereda',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
