# Generated by Django 4.2.23 on 2025-08-26 10:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0006_emergencycontact_phone_num_parent_signature_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parent',
            options={'ordering': ['registerd_date']},
        ),
        migrations.AddField(
            model_name='parent',
            name='registerd_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
