# Generated by Django 4.2.23 on 2025-08-26 10:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0007_alter_parent_options_parent_registerd_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='registerd_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
