# Generated by Django 4.2.23 on 2025-08-27 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0008_alter_parent_registerd_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parent',
            options={'ordering': ['-registerd_date']},
        ),
        migrations.AlterModelOptions(
            name='phonenumber',
            options={'ordering': ['-id']},
        ),
    ]
