# Generated by Django 4.2.23 on 2025-08-31 07:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0009_alter_parent_options_alter_phonenumber_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parent',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='registerd_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
