# Generated by Django 4.2.23 on 2025-09-01 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0010_alter_parent_options_phonenumber_registerd_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergencycontact',
            options={'ordering': ['-registration_date']},
        ),
        migrations.AlterModelOptions(
            name='parent',
            options={'ordering': ['-registerd_date']},
        ),
        migrations.AlterModelOptions(
            name='phonenumber',
            options={'ordering': ['-registerd_date']},
        ),
    ]
