# Generated by Django 4.2.23 on 2025-09-01 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0011_alter_emergencycontact_options_alter_parent_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonenumber',
            old_name='number_type',
            new_name='phone_type',
        ),
    ]
