# Generated by Django 4.2.23 on 2025-09-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0014_emergencycontact_image_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='image_file',
            field=models.ImageField(blank=True, default='jp.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='image_file',
            field=models.ImageField(blank=True, default='knowledge1_aFn8hfk.jpg', null=True, upload_to='pic'),
        ),
    ]
