# Generated by Django 4.2.23 on 2025-09-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0015_alter_emergencycontact_image_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='relationship',
            field=models.CharField(blank=True, choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('grandmother', 'Grandmother'), ('grandfather', 'Grandfather'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='owner',
            field=models.CharField(blank=True, choices=[('father', 'Father'), ('mother', 'Mother'), ('uncle', 'Uncle'), ('other', 'Other')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='phone_type',
            field=models.CharField(blank=True, choices=[('personal', 'Personal'), ('work phone', 'Work Phone'), ('other', 'Other')], max_length=30, null=True),
        ),
    ]
