# Generated by Django 4.2.23 on 2025-09-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0016_alter_emergencycontact_relationship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='education_level',
            field=models.CharField(blank=True, choices=[('none', 'No Formal Education'), ('primary', 'Primary'), ('secondary', 'Secondary'), ('highschool', 'High School'), ('diploma', 'Diploma'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='ocupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='work_place',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
