# Generated by Django 4.2.23 on 2025-09-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0018_alter_parent_first_name_alter_parent_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='first_name',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parent',
            name='last_name',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parent',
            name='middle_name',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parent',
            name='role',
            field=models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('grandmother', 'Grandmother'), ('grandfather', 'Grandfather'), ('other', 'Other')], default='unknown', max_length=50),
            preserve_default=False,
        ),
    ]
