# Generated by Django 4.2.23 on 2025-10-12 07:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0019_alter_parent_first_name_alter_parent_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
